# configuration.yaml
application:
  port: 3000
  host: 127.0.0.1
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
